apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: drsezginerdem/test-gitops:104
        name: flaskdemo
        ports:
        - containerPort: 80