apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default #every application belongs to a single project, if unspecified, an application belongs `defualt` project
  source:
    repoURL: https://github.com/sezginerdem/argocd-project.git #git repo
    targetRevision: HEAD
    path: kubernetes_objects
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true